"""Prepare a Neon project for the RAG example and generate ``.env.neon``."""

from __future__ import annotations

import os
import re
import shlex
import sys
from pathlib import Path

from neon_backend.provision import provision, write_env_file

ROOT = Path(__file__).parent
ENV_FILE = ROOT / ".env.neon"

_ENV_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")


def _read_generated_env(path: Path) -> dict[str, str]:
    """Read the shell-compatible values previously generated by this script."""

    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, raw_value = line.partition("=")
        if not separator or not _ENV_KEY.fullmatch(key):
            raise RuntimeError(f"invalid entry in {path.name} on line {line_number}")
        parsed = shlex.split(raw_value, posix=True)
        if len(parsed) != 1:
            raise RuntimeError(f"invalid value in {path.name} on line {line_number}")
        values[key] = parsed[0]
    return values


def run_setup() -> int:
    api_key = os.environ.get("NEON_API_KEY", "").strip()
    project_id = os.environ.get("NEON_PROJECT_ID", "").strip()
    missing = [
        name
        for name, value in (
            ("NEON_API_KEY", api_key),
            ("NEON_PROJECT_ID", project_id),
        )
        if not value
    ]
    if missing:
        raise RuntimeError(f"setup requires {', '.join(missing)}")

    existing = _read_generated_env(ENV_FILE)
    same_project = existing.get("NEON_PROJECT_ID") == project_id
    result = provision(
        api_key,
        project_id,
        existing_data_preparation_database_url=(
            existing.get("NEON_DATA_PREPARATION_DATABASE_URL") if same_project else None
        ),
        existing_search_database_url=(
            existing.get("NEON_SEARCH_DATABASE_URL") if same_project else None
        ),
    )
    write_env_file(
        str(ENV_FILE),
        {
            "NEON_PROJECT_ID": result.project_id,
            "NEON_DATA_PREPARATION_DATABASE_URL": (result.data_preparation_database_url),
            "NEON_SEARCH_DATABASE_URL": result.search_database_url,
        },
    )
    print(f"Neon setup complete. Generated {ENV_FILE.name}.")
    return 0


def main() -> int:
    try:
        return run_setup()
    except (RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
